"""Samo nesto probam4

Revision ID: 367dbc96d825
Revises: d17216397806
Create Date: 2024-06-25 19:05:33.733963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '367dbc96d825'
down_revision: Union[str, None] = 'd17216397806'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'email2')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('email2', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
