"""Samo nesto probam4

Revision ID: 5921b8883a21
Revises: 367dbc96d825
Create Date: 2024-06-25 23:27:00.841612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5921b8883a21'
down_revision: Union[str, None] = '367dbc96d825'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'check_in_date',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('bookings', 'check_out_date',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('guests', 'date_of_birth',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('payments', 'payment_date',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'payment_date',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=True)
    op.alter_column('guests', 'date_of_birth',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=True)
    op.alter_column('bookings', 'check_out_date',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=True)
    op.alter_column('bookings', 'check_in_date',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=True)
    # ### end Alembic commands ###
