"""Samo nesto probam

Revision ID: 9d0c2994d952
Revises: 
Create Date: 2024-06-25 18:56:00.089323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d0c2994d952'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rooms')
    op.drop_table('payments')
    op.drop_index('ix_guests_email', table_name='guests')
    op.drop_table('guests')
    op.drop_table('bookings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('booking_id', sa.INTEGER(), nullable=False),
    sa.Column('guest_id', sa.INTEGER(), nullable=True),
    sa.Column('room_id', sa.INTEGER(), nullable=True),
    sa.Column('check_in_date', sa.DATETIME(), nullable=True),
    sa.Column('check_out_date', sa.DATETIME(), nullable=True),
    sa.Column('total_amount', sa.FLOAT(), nullable=True),
    sa.Column('booking_status', sa.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.guest_id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], ),
    sa.PrimaryKeyConstraint('booking_id')
    )
    op.create_table('guests',
    sa.Column('guest_id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('email', sa.VARCHAR(length=50), nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), nullable=True),
    sa.Column('address', sa.VARCHAR(length=50), nullable=True),
    sa.Column('date_of_birth', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('guest_id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index('ix_guests_email', 'guests', ['email'], unique=1)
    op.create_table('payments',
    sa.Column('payment_id', sa.INTEGER(), nullable=False),
    sa.Column('booking_id', sa.INTEGER(), nullable=True),
    sa.Column('payment_date', sa.DATETIME(), nullable=True),
    sa.Column('payment_method', sa.VARCHAR(length=20), nullable=True),
    sa.Column('payment_status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('email2', sa.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], ),
    sa.PrimaryKeyConstraint('payment_id'),
    sa.UniqueConstraint('booking_id')
    )
    op.create_table('rooms',
    sa.Column('room_id', sa.INTEGER(), nullable=False),
    sa.Column('room_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('price_per_night', sa.FLOAT(), nullable=True),
    sa.Column('availability_status', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('room_id')
    )
    # ### end Alembic commands ###
